### ISSUE TITLE
'nodeModulesToVendor' in ember-cli-build fails

### ISSUE THREAD

**Issue by allthesignals** [auth0-community/auth0-ember-samples#3]
`ember serve` throws:

```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor & appJS)] failed with:
Error: ENOENT: no such file or directory, stat '/Users/mgardner/cityxcity/tmp/source_map_concat-input_base_path-729yTT8I.tmp/0/vendor/auth0.js'
    at Error (native)
    at Object.fs.statSync (fs.js:1000:11)
    at FSMonitor._measure (/Users/mgardner/cityxcity/node_modules/heimdalljs-fs-monitor/index.js:66:21)
    at Object.statSync (/Users/mgardner/cityxcity/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at Concat.keyForFile (/Users/mgardner/cityxcity/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:87:20)
    at Array.map (native)
    at Concat.CachingWriter._conditionalBuild (/Users/mgardner/cityxcity/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:109:65)
    at /Users/mgardner/cityxcity/node_modules/broccoli-concat/node_modules/broccoli-plugin/read_compat.js:61:34
    at tryCatch (/Users/mgardner/cityxcity/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/mgardner/cityxcity/node_modules/rsvp/dist/rsvp.js:538:13)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (/Users/mgardner/cityxcity/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/mgardner/cityxcity/node_modules/broccoli-merge-trees/index.js:42:10)
    at BroccoliMergeTrees (/Users/mgardner/cityxcity/node_modules/broccoli-merge-trees/index.js:36:53)
    at module.exports (/Users/mgardner/cityxcity/node_modules/ember-cli/lib/broccoli/merge-trees.js:8:14)
    at EmberApp.javascript (/Users/mgardner/cityxcity/node_modules/ember-cli/lib/broccoli/ember-app.js:1278:10)
    at EmberApp.toArray (/Users/mgardner/cityxcity/node_modules/ember-cli/lib/broccoli/ember-app.js:1640:10)
    at EmberApp.toTree (/Users/mgardner/cityxcity/node_modules/ember-cli/lib/broccoli/ember-app.js:1662:30)
    at module.exports (/Users/mgardner/cityxcity/ember-cli-build.js:41:14)
    at CoreObject.setupBroccoliBuilder (/Users/mgardner/cityxcity/node_modules/ember-cli/lib/models/builder.js:70:19)
    at CoreObject.init (/Users/mgardner/cityxcity/node_modules/ember-cli/lib/models/builder.js:50:10)
```

```
// ember-cli-build.js
  var app = new EmberApp(defaults, {
    fingerprint: {
      prepend: config.prepend,
      enabled: false,
      exclude: [
        'images/layers-2x.png',
        'images/layers.png',
        'images/marker-icon-2x.png',
        'images/marker-icon.png',
        'images/marker-shadow.png',
        'images/icons',
        'images/icons/*'
      ]
    },
    nodeModulesToVendor: [
      'node_modules/auth0-js/build',
    ],
  });

  app.import('bower_components/d3/d3.js');
  app.import('vendor/auth0.js');
```

**Comment by allthesignals** [comment]
auth0.js never seems to make it inside vendor/0/.

**Comment by allthesignals** [comment]
Upgrading `ember-cli` - maybe it's a broccoli issue?

**Comment by beardaway** [comment]
Hey there!

Sorry for such huge delay in response but we haven't had internal bandwidth to maintain those repos and we kinda outsourced it community. We're currently working on establishing some strategies around that. I'm closing this issues and will re-open it once we decide on some actions! Thank you for understanding!
